use std::fmt;

use pion_utils::numeric_conversions::TruncateFrom;
use pion_utils::symbol::Symbol;

/// Names for local variable *binders* - ie
/// - `Expr::Let`
/// - `Expr::FunType`
/// - `Expr::FunLit`
/// - `Expr::Match`
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum BinderName {
    /// An underscore pattern occured in the source code
    Underscore,
    /// An identifier pattern occured in the source code
    User(Symbol),
}

impl fmt::Display for BinderName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Underscore => write!(f, "_"),
            Self::User(symbol) => write!(f, "{symbol}"),
        }
    }
}

impl From<FieldName> for BinderName {
    fn from(field_name: FieldName) -> Self {
        match field_name {
            FieldName::User(symbol) => Self::User(symbol),
        }
    }
}

/// Names for local variables *uses* - ie `Expr::Local`
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum LocalName {
    /// An `Expr::Local` generated by elaboration
    Generated,
    /// An identifier expr occured in the source code
    User(Symbol),
}

/// Names for record fields - ie `Expr::RecordType` and `Expr::RecordLit`
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum FieldName {
    User(Symbol),
}
impl FieldName {
    pub fn tuple(index: u32) -> Self { Self::User(Symbol::tuple_index(index)) }
}

impl fmt::Display for FieldName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::User(symbol) => write!(f, "{symbol}"),
        }
    }
}

impl FieldName {
    pub fn are_tuple_field_names(field_names: impl IntoIterator<Item = Self>) -> bool {
        field_names
            .into_iter()
            .enumerate()
            .all(|(idx, name)| name == Self::tuple(u32::truncate_from(idx)))
    }
}
