[package]
name = "pion-lexer"

edition = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
memchr = "2.6.4"
pion-utils = { path = "../pion-utils" }

[dev-dependencies]
expect-test = { version = "1.4.1" }
