[package]
name = "stepper-fuzz"

version = "0.0.0"
edition = "2021"

publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.stepper]
path = ".."

[[bin]]
name = "eval"
path = "src/eval.rs"

test  = false
doc   = false
bench = false
