[package]
name = "pion-printer"

edition.workspace = true
version.workspace = true

[dependencies]
pion-symbol = { path = "../pion-symbol" }

bumpalo = { workspace = true }

pretty = { version = "0.12.3" }

[lints]
workspace = true
